name: ws-bom Build and publish Docker images
on:
  push:
    branches: [ "main" ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Build & push docker image
    runs-on: ubuntu-latest    
    env:
      REPOSITORY: ${{ github.repository }}
      REGISTRY: wsdev.azurecr.io
      PROJECT: ws-bom-sample-basic
      AZURE_CONTAINER_REGISTRY_USER: ${{ secrets.AZURE_CONTAINER_REGISTRY_USER }}
      AZURE_CONTAINER_REGISTRY_PWD: ${{ secrets.AZURE_CONTAINER_REGISTRY_PWD }}
    steps: 
      - name: Checkout
        id: checkout-repo
        uses: actions/checkout@v3
      - name: Login to Azure Container Registry
        id: logn-ACR
        uses: docker/login-action@v2  
        with:
          registry: ${{ env.REGISTRY }}      
          username: ${{ env.AZURE_CONTAINER_REGISTRY_USER }}
          password: ${{ env.AZURE_CONTAINER_REGISTRY_PWD }}   
      - name: Build bom
        id: build-push-bom
        if: (true)
        run: |    
          # docker build --progress=plain -f ./src/bowl/Dockerfile -t ${{ env.PROJECT }}-bowl:latest  .
          # docker tag ${{ env.PROJECT }}-bowl:latest  ${{ env.REGISTRY }}/${{ env.PROJECT }}-bowl:latest
          # docker push ${{ env.REGISTRY }}/${{ env.PROJECT }}-bowl:latest  
          docker build --progress=plain -f ./src/oven/Dockerfile -t ${{ env.PROJECT }}-oven:latest  ./src/oven
          docker tag ${{ env.PROJECT }}-oven:latest  ${{ env.REGISTRY }}/${{ env.PROJECT }}-oven:latest
          docker push ${{ env.REGISTRY }}/${{ env.PROJECT }}-oven:latest    
          docker build --progress=plain -f ./src/mixer/Dockerfile -t ${{ env.PROJECT }}-mixer:latest  .
          docker tag ${{ env.PROJECT }}-mixer:latest  ${{ env.REGISTRY }}/${{ env.PROJECT }}-mixer:latest
          docker push ${{ env.REGISTRY }}/${{ env.PROJECT }}-mixer:latest                  
